app = "infojobs-map"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "mad"

[env]
PORT = "8080"

[experimental]
auto_rollback = true

[[services]]
internal_port = 8_080
processes = [ "app" ]
protocol = "tcp"
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

  [[services.ports]]
  force_https = true
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  timeout = "2s"